### ISSUE TITLE
system call failed: Cannot allocate memory 

### ISSUE THREAD

**Issue by drpatshahbs** [ChrisMaherLab/SV-Hotspot#1]
Hi,
It appears that while processing my dataset i have a 'cannot allocate memory' error. However, I have almost 40 GBs of RAM available on my machine with a Terabyte of free HDD space. 
Is there a way to force SV-Hotspot to allocate memory?

Thanks
Parth

**Comment by Eteleeb** [comment]
Hi Parth, 

Thank you for testing our tool. How big your dataset is?. We have been able to run the tool for several cohorts using less memory size (not sure about the heap though). 40 GBs seems to be enough to run the tool. Can you try to run the tool for one chromosome only using the option -C chr#?. If this works, then it is definitely a memory issue. 

Just to make sure, is the error "cannot allocate memory" or "cannot allocate vector of size xxx"?. 

Regards, 

-Abdallah

**Comment by drpatshahbs** [comment]
Hi,
I tried to restrict this to 1 chromosome- chromosome 5 - however i have the same memory error. 

<img width="1115" alt="Screen Shot 2021-01-28 at 1 25 21 PM" src="https://user-images.githubusercontent.com/77735371/106182082-5ed03e00-616c-11eb-8030-2436858ebbce.png">

**Comment by Eteleeb** [comment]
Can you try to increase the swap value?. On linux you can run the following commands: 

#get the current swap value    
cat /proc/sys/vm/swappiness
10
#Access the swap configuration
gksudo leafpad /etc/sysctl.conf

#Increase the swap usage to 30 (default is 60)
vm.swappiness=30

**Comment by drpatshahbs** [comment]
Hey,

I think this was specific to the way my mac osx is set up. I tried this on another ubuntu machine and the issue disappeared. 
Thank you!

**Comment by Eteleeb** [comment]
I am glad to hear that the issue was resolved.
